name: error-check
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run eslint on changed files
        run: bash .scripts/lintCheck.sh ${{ github.token }}
        